title = "imm3rsively"
baseURL = "http://imm3rsively.com/"
tags = ["education", "conference", "learning"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = "effective, equitable education"
    author = "Sherif Abushadi"
    description = "the conference for people who suspect the future of education has arrived"
    logoBig = "/images/logo.png"
    logoSmall = "/images/logo.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/logo.png"
    # twitter = "imm3rsively"
    # linkedin = "imm3rsively"
    # github = "imm3rsively"
    email = "sherif@amgando.org"
    googleTagManager = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "People"
    url  = "/#people"
    weight = 2
[[menu.main]]
    name = "Tickets"
    url  = "/#tickets"
    weight = 3
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4
